# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly

exclude: ^src/auditwheel/_vendor/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^cache/
  - id: mixed-line-ending
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 77039ccbba72c8aede339c5f8ae29b42aced0a2e  # frozen: v0.15.18
  hooks:
  - id: ruff-check
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
    exclude: tests/integration/.*/.*|tests/integration/quick_check_numpy.py|tests/unit/test_wheel_abi.py|scripts/calculate_symbol_versions.py
    args: ["--python-version=3.10"]
    additional_dependencies:
      - nox
      - packaging
      - pyelftools>=0.33
      - pytest
      - types-docker
      - types-requests

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: e3eebf65325ccc992422292cb7a4baee967cf815  # frozen: v1.26.1
  hooks:
  - id: zizmor
